/* ========================================================================
   OPTIMIZACIÓN DE TAXONOMÍA (Ahorro de bytes y consistencia)
   ======================================================================== */
window.CTX = {
  PROF: 'PROFESSIONAL',
  UNIV: 'UNIVERSITY',
  PERS: 'PERSONAL',
};

window.CAT = {
  DEV: 'DEV',
  DES: 'DESIGN',
  VID: 'VIDEO',
  ART: 'ART',
};

// Herramientas más repetidas (Opcional, pero ayuda mucho a reducir peso)
window.T = {
  HTML: 'HTML',
  CSS: 'CSS',
  JS: 'Javascript',
  CS: 'C#',
  UNITY: 'Unity',
  FIGMA: 'Figma',
  WEB: 'Web',
  FRONT: 'Frontend',
  UI: 'UI',
  UX: 'UX',
  PHOTO: 'Photoshop',
  ILUS: 'Ilustrator',
  UNREAL: 'Unreal Engine',
  MAYA: 'Autodesk Maya',
  DAVINCI: 'DaVinci Resolve',
  EDIT: 'Edición de Video',
  VID: 'Video',
  YT: 'YouTube',
  THUMB: 'Miniaturas',
  TW: 'Twitch',
  COM: 'Comunitario',
  PY: 'Python',
  SCR: 'Script',
  SOFT: 'Software',
};

window.PROJECT_CONFIG = {
  paths: {
    [CAT.DEV]: '../assets/images/dev/',
    [CAT.DES]: '../assets/images/design/',
    [CAT.ART]: '../assets/images/ilustraciones/',
    [CAT.VID]: '../assets/images/video/', // Opcional
    DEFAULT: '../assets/images/',
  },
};

/* ========================================================================
   1. PORTAFOLIO PRINCIPAL (DEV + DESIGN + VIDEO)
   ======================================================================== */
window.mainPortfolio = [
  {
    title: 'Wedding invitation (custom)',
    fileName: 'boda_hermano_1_persona.webp',
    link: '=',
    desc: 'Client request: wedding invitation design with personalized settings; print-ready deliverables.',
    pdfOnly: 'false',
    tools: [T.PHOTO],
    category: CAT.DES,
    context: CTX.PERS,
  },
  {
    title: 'Thumbnail: Nostalgic Minecraft Video',
    fileName: 'Minecraft-en-2010.webp',
    link: '=',
    desc: 'Thumbnail design for a video about the early stages of Minecraft development.',
    pdfOnly: 'false',
    tools: [T.PHOTO, T.THUMB, T.VID, T.YT],
    category: CAT.DES,
    context: CTX.PERS,
  },
  {
    title: 'Mini edition: Easter invitation',
    link: 'https://youtube.com/shorts/Fgi9CA35Onc?feature=share',
    desc: 'Short video that presents the design of an invitation for Holy Week.',
    pdfOnly: 'false',
    tools: [T.DAVINCI, T.EDIT, T.VID, T.YT],
    category: CAT.VID,
    context: CTX.PERS,
  },
  {
    title: 'AR Demo: 3D modeling',
    link: 'https://youtube.com/shorts/b6hb9cotBcM?feature=share',
    desc: 'Demonstration of 3D modeling in Augmented Reality using Autodesk Maya and Unity.',
    pdfOnly: 'false',
    tools: [T.MAYA, T.UNITY, T.VID, T.YT],
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Closing overlay for streaming',
    fileName: 'Fondo-offline-v1.avif',
    link: 'https://www.twitch.tv/tarquitet',
    desc: 'Overlay design for live broadcasts (Twitch/YouTube); deliverables in PNG and PSD.',
    pdfOnly: 'false',
    tools: [T.PHOTO, T.TW, T.VID, T.YT],
    category: CAT.DES,
    context: CTX.PERS,
  },
  {
    title: 'G.O.U.G Logo',
    fileName: 'GOUG-logo.webp',
    link: 'https://www.curseforge.com/minecraft/modpacks/goug-optimized',
    desc: 'Logo design for the G.O.U.G modpack; includes vector and raster versions.',
    pdfOnly: 'false',
    tools: [T.PHOTO],
    category: CAT.DES,
    context: CTX.PERS,
  },
  {
    title: 'Front advertisement for Church',
    fileName: 'anuncio-gold-papa.avif',
    link: '=',
    desc: 'Front advertisement design for printing and display on the facade of a local church.',
    pdfOnly: 'false',
    tools: [T.PHOTO],
    category: CAT.DES,
    context: CTX.PROF,
  },
  {
    title: 'Redesign: Horeb Bible Institute',
    fileName: 'IBHOREB-1.avif',
    link: '=',
    desc: 'Visual identity redesign for Horeb Bible Institute, aimed at legibility and printed applications.',
    pdfOnly: 'false',
    tools: [T.PHOTO],
    category: CAT.DES,
    context: CTX.PROF,
  },
  {
    title: 'Front advertisement (Church)',
    fileName: 'IUJ-GLORIA.webp',
    link: '=',
    desc: 'Front advertisement design for printing and display on the facade of a local church.',
    pdfOnly: 'false',
    tools: [T.PHOTO],
    category: CAT.DES,
    context: CTX.PROF,
  },
  {
    title: 'Thumbnail: modpack installation',
    fileName: 'NostalgiCraft-Modpack.webp',
    link: '=',
    desc: 'Thumbnail designed for a tutorial on how to install a modpack in Minecraft.',
    pdfOnly: 'false',
    tools: [T.PHOTO, T.THUMB, T.VID, T.YT],
    category: CAT.DES,
    context: CTX.PERS,
  },
  {
    title: 'Layout: job offer (ATOM Solutions)',
    fileName: 'oferta_laboral_tecnico.webp',
    link: '=',
    desc: 'Layout of the job advertisement for ATOM Solutions; web and print-ready deliverables.',
    pdfOnly: 'false',
    tools: [T.PHOTO],
    category: CAT.DES,
    context: CTX.PROF,
  },
  {
    title: 'Frame Edit — Cities in Dust',
    fileName: 'Edicion_Fotograma_CitiesInDust.avif',
    link: '=',
    desc: 'Quick editing (≤1 h) of a frame of the music video clip for an academic project.',
    pdfOnly: 'false',
    tools: [T.PHOTO, T.VID],
    category: CAT.DES,
    context: CTX.UNIV,
  },
  {
    title: 'Final render — comic (university)',
    fileName: 'preview-comic-render.webp',
    link: '/assets/pdf/university/DavidPinto_ComicFinal_Unido_compressed.pdf',
    desc: 'Final render of a comic made individually for the Rendering subject.',
    pdfOnly: 'false',
    tools: [T.MAYA, T.PHOTO],
    category: CAT.DES,
    context: CTX.PERS,
  },
  {
    title: 'Mockup proposal — Multimedia Day',
    fileName: 'smartmockups_l7w4oeot.avif',
    link: '=',
    desc: 'Logo and mockup proposal for the Multimedia Engineer\'s Day; includes presentations and application mockups.',
    pdfOnly: 'false',
    tools: [T.ILUS, T.PHOTO],
    category: CAT.DES,
    context: CTX.UNIV,
  },
  {
    title: 'Retro CGI Art #02',
    fileName: 'test_2.webp',
    link: '=',
    desc: 'CGI work inspired by retro aesthetics prior to the 2000s.',
    pdfOnly: 'false',
    tools: [T.MAYA, T.PHOTO],
    category: CAT.DES,
    context: CTX.PERS,
  },
  {
    title: 'Retro CGI Art #01',
    fileName: 'test_3.webp',
    link: '=',
    desc: 'CGI work inspired by retro aesthetics prior to the 2000s.',
    pdfOnly: 'false',
    tools: [T.MAYA, T.PHOTO],
    category: CAT.DES,
    context: CTX.PERS,
  },
  {
    title: 'Fancy Land Logo',
    fileName: 'Texto-Fancy-Land.avif',
    link: '=',
    desc: 'Logo design for a Minecraft series; includes scalable files.',
    pdfOnly: 'false',
    tools: [T.PHOTO],
    category: CAT.DES,
    context: CTX.PERS,
  },
  {
    title: 'Dreams come true',
    fileName: 'Transmedia - composicion narrativa - Montaje Final - David Pinto.webp',
    link: '=',
    desc: 'Conceptual design about the expression of a dream world in visual format.',
    pdfOnly: 'false',
    tools: [T.PHOTO],
    category: CAT.DES,
    context: CTX.UNIV,
  },
  {
    title: 'Level design (Unreal Engine)',
    fileName: 'unreal5.avif',
    link: '=',
    desc: 'Lighting and level design for an academic project in Unreal Engine.',
    pdfOnly: 'false',
    tools: [T.CS, T.UNREAL],
    category: CAT.DEV,
    context: CTX.UNIV,
  },
  {
    title: 'Logo redesign — Verdad & Fe',
    fileName: 'V&F-6.avif',
    link: 'https://www.verdadyfe.org/',
    desc: 'Redesign of visual identity for the Verdad & Fe ministry; prepared for web and print.',
    pdfOnly: 'false',
    tools: [T.PHOTO],
    category: CAT.DES,
    context: CTX.PROF,
  },
  {
    title: 'Thumbnail: Parkour Minecraft',
    fileName: '200-Parkours---reto-1.webp',
    link: '=',
    desc: 'Thumbnail design for a parkour video in Minecraft.',
    pdfOnly: 'false',
    tools: [T.PHOTO, T.THUMB, T.VID, T.YT],
    category: CAT.DES,
    context: CTX.PERS,
  },
  {
    title: 'Ministerial website — Truth & Faith',
    fileName: 'verdadyfe.avif',
    link: 'https://www.verdadyfe.org/',
    desc: 'Official landing page developed with HTML/CSS/JS for the Verdad & Fe ministry.',
    pdfOnly: 'false',
    tools: [T.HTML, T.CSS, T.JS, T.FRONT, 'SEO'],
    category: CAT.DEV,
    context: CTX.PROF,
  },
  {
    title: 'Official site — Tarquitet',
    fileName: 'tarquitet-site.avif',
    link: '#',
    desc: 'Personal portfolio site with responsive design and project visualization.',
    pdfOnly: 'false',
    tools: [T.HTML, T.CSS, T.JS, 'Portfolio', T.FRONT, 'Web Design', 'Backend'],
    category: CAT.DEV,
    context: CTX.PROF,
  },
  {
    title: 'Tarquitet (previous version)',
    fileName: 'tarquitet-old-site.avif',
    link: '/ver1/index.html',
    desc: 'Previous version of the portfolio site (archived).',
    pdfOnly: 'false',
    tools: [T.HTML, T.CSS, T.JS, 'Portfolio', T.FRONT, 'Web Design', 'Backend'],
    category: CAT.DEV,
    context: CTX.PROF,
  },
  {
    title: 'Builtechraft Web (1st ver)',
    fileName: 'Builtechraft-web-2024.avif',
    link: 'https://tarquitet.github.io/Builtechraft-Web/',
    desc: 'Website for multiplayer server project; includes project presentation and server details.',
    pdfOnly: 'false',
    tools: [T.HTML, T.CSS, T.JS, T.FRONT, 'Web Design', 'Minecraft', T.WEB],
    category: CAT.DEV,
    context: CTX.UNIV,
  },
  {
    title: 'Builtechraft Web',
    fileName: 'btc-2026.avif',
    link: 'https://builtechraft.tarquitet.com/',
    desc: 'Website for multiplayer server project; includes project presentation and server details.',
    pdfOnly: 'false',
    tools: [T.HTML, T.CSS, T.JS, T.FRONT, 'Web Design', 'Minecraft', T.WEB],
    category: CAT.DEV,
    context: CTX.PROF,
  },
  {
    title: 'Horeb Web Bible Institute',
    fileName: 'instituto-web.avif',
    link: 'https://pagina-instituto.pages.dev/',
    desc: 'Website for the Bible institute; includes presentation of the institute, academic programs and contact.',
    pdfOnly: 'false',
    tools: [T.HTML, T.CSS, T.JS, T.FRONT, 'Web Design', 'Academic', T.WEB],
    category: CAT.DEV,
    context: CTX.PROF,
  },
  {
    title: '3D Virtual Gym App',
    desc: 'Mobile application with 360° demos and biomechanical explanations; UI prototype included.',
    fileName: 'https://raw.githubusercontent.com/pintomultimedia2002/GymApp_1_2024/refs/heads/main/Assets/prototipo-demo.png',
    link: 'https://github.com/pintomultimedia2002/GymApp_1_2024',
    pdfOnly: 'false',
    tools: [T.UNITY, T.CS, 'UI Mobile'],
    category: CAT.DEV,
    context: CTX.UNIV,
  },
  {
    title: 'Smart Sudoku Solver',
    desc: 'Sudoku generator and solver using optimized backtracking; research prototype.',
    fileName: 'https://raw.githubusercontent.com/pintomultimedia2002/Sudoku_Intelligent_Backtracking/refs/heads/master/sudokugenerado.png',
    link: 'https://github.com/pintomultimedia2002/Sudoku_Intelligent_Backtracking',
    pdfOnly: 'false',
    tools: [T.CS, 'Backtracking', 'IA'],
    category: CAT.DEV,
    context: CTX.UNIV,
  },
  {
    title: 'C.I.P.S Puzzle Solver',
    desc: 'Experimental AI mini-game that solves numerical puzzles using heuristics.',
    fileName: 'https://raw.githubusercontent.com/pintomultimedia2002/CIPS_Intelligent_Puzzle_Solver/refs/heads/master/puzzle-solved.jpg',
    link: 'https://github.com/pintomultimedia2002/CIPS_Intelligent_Puzzle_Solver',
    pdfOnly: 'false',
    tools: [T.CS, 'Heurística', 'IA'],
    category: CAT.DEV,
    context: CTX.UNIV,
  },
  {
    title: 'Agent Wumpus World',
    desc: 'Simulation of a rational agent based on propositional logic for decision making.',
    fileName: 'https://raw.githubusercontent.com/pintomultimedia2002/wumpus-world-javascript/refs/heads/main/src/resources/wampus.png',
    link: 'https://github.com/pintomultimedia2002/wumpus-world-javascript',
    pdfOnly: 'false',
    tools: [T.JS, 'Lógica', 'IA Clásica'],
    category: CAT.DEV,
    context: CTX.UNIV,
  },
  {
    title: 'A* algorithm (pathfinding)',
    desc: 'Implementation of the A* algorithm to search for optimal paths; includes visual demo.',
    fileName: 'https://raw.githubusercontent.com/pintomultimedia2002/A_star_algorithm_Javascript/refs/heads/main/wampus-ia.png',
    link: 'https://github.com/pintomultimedia2002/A_star_algorithm_Javascript',
    pdfOnly: 'false',
    tools: [T.JS, 'Pathfinding', 'Algoritmos'],
    category: CAT.DEV,
    context: CTX.UNIV,
  },
  {
    title: 'CarVoice Assistant',
    desc: 'Voice assistant for vehicular environments with prototype web interface and integrations.',
    fileName: 'https://raw.githubusercontent.com/pintomultimedia2002/carvoice-assist/refs/heads/main/assets/asistant-2.png',
    link: 'https://github.com/pintomultimedia2002/carvoice-assist',
    pdfOnly: 'false',
    tools: [T.HTML, T.CSS, T.JS, T.FRONT, 'Web Design', 'Voiceflow', 'Chatbot', T.WEB],
    category: CAT.DEV,
    context: CTX.UNIV,
  },
  {
    title: 'Algebrain App',
    desc: 'UX-focused educational algebra app; Interactive exercises and progress tracking.',
    fileName: 'https://raw.githubusercontent.com/pintomultimedia2002/Algebrain-App/refs/heads/main/resources/images/algebrain-demo-4.png',
    link: 'https://github.com/pintomultimedia2002/Algebrain-App',
    pdfOnly: 'false',
    tools: [T.HTML, T.CSS, T.JS, T.FRONT, 'Web Design', 'eLearning', 'Web App', 'Mobile', T.WEB],
    category: CAT.DEV,
    context: CTX.UNIV,
  },
  {
    title: '360° VR experience',
    fileName: 'audio-video-360.avif',
    link: 'https://www.youtube.com/watch?v=Z8sgOhYMAl4',
    desc: 'Immersive VR horror experience created in Unity with 3D audio and interactive elements.',
    pdfOnly: 'false',
    tools: [T.UNITY, 'VR', 'Audio 3D', T.CS, 'Immersiva', '360°', 'Video', 'Audio', 'XR'],
    category: CAT.DEV,
    context: CTX.UNIV,
  },
  {
    title: 'OpenGL 3D simulation',
    fileName: 'unity-opengl-web.avif',
    link: 'https://relaxed-valkyrie-75101a.netlify.app/',
    desc: 'Collection minigame with basic physics, implemented for WebGL deployment.',
    pdfOnly: 'false',
    tools: [T.UNITY, 'Simulación', '3D', 'Físicas', 'WebGL', T.WEB, T.CS],
    category: CAT.DEV,
    context: CTX.UNIV,
  },
  {
    title: 'Sonórus — UI Redesign',
    fileName: 'Sonorus-Figma.avif',
    link: 'https://www.figma.com/design/lClUfMJDAuqfEhvXN6IN2B/Untitled?node-id=0-1&t=UD8TxB4UupRydWWD-1',
    desc: 'Interface redesign for music application; prototypes in Figma and UI kit.',
    pdfOnly: 'false',
    tools: [T.FIGMA, 'UI Design', 'Prototyping', 'Redesign', T.UI, T.UX, 'Mobile Design'],
    category: CAT.DES,
    context: CTX.UNIV,
  },
  {
    title: '4 Better Pets — Mobile App',
    fileName: '4better-pets-app.avif',
    link: 'https://www.figma.com/design/8LDG3cejNOO7Re9Z6MMrfU/4-BETTER-PETS?node-id=0-1&t=fkQtYiNLOuIEM5Uo-1',
    desc: 'Mobile prototype to facilitate pet adoption; includes UX research and prototyping.',
    pdfOnly: 'false',
    tools: [T.FIGMA, 'UX Research', 'Mobile Design', 'Prototyping', T.UI, T.UX, 'App Design'],
    category: CAT.DES,
    context: CTX.UNIV,
  },
  {
    title: 'UI Redesign — Rappi',
    fileName: 'RedisenoRappi-Figma.avif',
    link: 'https://www.figma.com/design/W8tY2RtS3hM7B9BQjJgpiB/David-Pinto---Redise%C3%B1o-Rappi?node-id=0-1&t=UmSvMcQEsiyU7y4s-1',
    desc: 'Redesign proposal focused on improving user experience and visual consistency.',
    pdfOnly: 'false',
    tools: [T.FIGMA, 'UI Kit', 'Redesign', T.UI, T.UX, 'App Design'],
    category: CAT.DES,
    context: CTX.UNIV,
  },
  {
    title: 'In-Mortal Transmedia',
    desc: 'Transmedia narrative exploration of the evolution of ideas; project site and narrative assets.',
    fileName: 'https://static.wixstatic.com/media/5d4a70_7d7ad22b0b4f4defbc347b359909bcb1~mv2.jpg/v1/fill/w_2146,h_1229,al_c,q_90,enc_avif,quality_auto/5d4a70_7d7ad22b0b4f4defbc347b359909bcb1~mv2.jpg',
    link: 'https://pintodavid2002.wixsite.com/in-mortal',
    pdfOnly: 'false',
    tools: ['Storytelling', 'Wix', 'Concept Art', 'Narrative', 'Transmedia', 'Web Design', T.WEB, T.UX],
    category: CAT.DEV,
    context: CTX.PERS,
  },
  {
    title: 'Planty — Instructional Video',
    date: '2023-05-20',
    channel: 'CLIENTE',
    link: 'https://www.youtube.com/watch?v=1AMhkDXVkqU',
    desc: 'Instructional video for Planty (client); includes step-by-step guide.',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Planty — Behind the scenes',
    date: '2023-05-25',
    channel: 'CLIENTE',
    link: 'https://www.youtube.com/watch?v=scgv4lL-4vk',
    desc: 'Behind-the-scenes footage of Planty\'s production.',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Antioquia Missionary Church — Event',
    date: '2021-07-15',
    channel: 'CLIENTE',
    link: 'https://www.youtube.com/watch?v=zi_l5z1Yx6s',
    desc: 'Registration and editing of event for Iglesia Misionera Antioquia (client).',
    category: CAT.VID,
    context: CTX.PERS,
  },
  {
    title: 'Trailer — Algebrain',
    date: '2024-02-10',
    channel: 'PROMO',
    link: 'https://www.youtube.com/watch?v=9rP3nJe5S4g',
    desc: 'Promotional trailer of the Algebrain application showing functionalities and UI.',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Parody commercial — GymApp',
    date: '2024-01-15',
    channel: 'COMERCIAL',
    link: 'https://www.youtube.com/watch?v=QWK7JctMbug',
    desc: 'Parody commercial created as a promotional piece for GymApp.',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Radio soap opera — Suspense',
    date: '2023-06-10',
    channel: 'ARCHIVO',
    link: 'https://www.youtube.com/watch?v=VJC3mEY-dFU',
    desc: 'Production of radio soap opera in suspense genre (archive).',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Minidocumentary — Electronic art',
    date: '2022-11-10',
    channel: 'DOCU',
    link: 'https://www.youtube.com/watch?v=P4X0pvVxqVE',
    desc: 'Minidocumentary on electronic art practices.',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Brainstorming — Brock Project',
    date: '2022-09-05',
    channel: 'ARCHIVO',
    link: 'https://www.youtube.com/watch?v=ijmfr-FB1dM',
    desc: 'Brainstorming session and prototype material (file).',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Stop motion — Pixelation',
    date: '2022-04-15',
    channel: 'ANIMACIÓN',
    link: 'https://www.youtube.com/watch?v=ui06UdetAPg',
    desc: 'Stop-motion animation project using pixelation techniques.',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Visual narrative — Ethics',
    date: '2020-08-20',
    channel: 'ARCHIVO',
    link: 'https://www.youtube.com/watch?v=DR1FwQc-9rQ',
    desc: 'Academic project on visual narrative and ethical issues.',
    context: CTX.UNIV,
    category: CAT.VID,
  },
  {
    title: 'Synchronized 3D Render',
    date: '2023-11-15',
    channel: 'ARCHIVO',
    link: 'https://www.youtube.com/watch?v=VcCDOt0Uujk',
    desc: '3D rendering synchronized with animation (file).',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: '3D animated sack',
    date: '2023-10-20',
    channel: 'ARCHIVO',
    link: 'https://www.youtube.com/watch?v=wKekfdNC3ZY',
    desc: 'Short film/3D animation starring a sack character (file).',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Playblast — Electro Swing',
    date: '2023-09-05',
    channel: 'ARCHIVO',
    link: 'https://youtu.be/v3VPVmA7qOs',
    desc: 'Animation playblast for musical project (file).',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Playblast & edit — Cops',
    date: '2023-08-15',
    channel: 'ARCHIVO',
    link: 'https://youtu.be/V3ABRvOuce0',
    desc: 'Compilation of playblasts and editing for Cops project (archive).',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Timelapse — GymApp Development',
    date: '2024-01-20',
    channel: 'DEVLOG',
    link: 'https://www.youtube.com/watch?v=ANcyGAwcUac',
    desc: 'Timelapse of the GymApp prototype development process.',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Digital drawing — My beginnings',
    date: '2022-03-20',
    channel: 'ARTE',
    link: 'https://www.youtube.com/watch?v=QV04Wh2BU0E',
    desc: 'Series of early digital drawings showing personal evolution.',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Tutorial — OOP in Java',
    date: '2020-05-15',
    channel: 'TUTORIAL',
    link: 'https://www.youtube.com/watch?v=qIxRbcXezWU',
    desc: 'Tutorial on object-oriented programming in Java.',
    category: CAT.VID,
    context: CTX.UNIV,
  },];

/* ========================================================================
   2. GALERÍA VISUAL (ARTE)
   ======================================================================== */
window.galleryData = [];
