/* ========================================================================
   OPTIMIZACIÓN DE TAXONOMÍA (Ahorro de bytes y consistencia)
   ======================================================================== */
window.CTX = {
  PROF: 'PROFESSIONAL',
  UNIV: 'UNIVERSITY',
  PERS: 'PERSONAL',
};

window.CAT = {
  DEV: 'DEV',
  DES: 'DESIGN',
  VID: 'VIDEO',
  ART: 'ART',
};

// Herramientas más repetidas (Opcional, pero ayuda mucho a reducir peso)
window.T = {
  HTML: 'HTML',
  CSS: 'CSS',
  JS: 'Javascript',
  CS: 'C#',
  UNITY: 'Unity',
  FIGMA: 'Figma',
  WEB: 'Web',
  FRONT: 'Frontend',
  UI: 'UI',
  UX: 'UX',
  PHOTO: 'Photoshop',
  ILUS: 'Ilustrator',
  UNREAL: 'Unreal Engine',
  MAYA: 'Autodesk Maya',
  DAVINCI: 'DaVinci Resolve',
  EDIT: 'Edición de Video',
  VID: 'Video',
  YT: 'YouTube',
  THUMB: 'Miniaturas',
  TW: 'Twitch',
  COM: 'Comunitario',
  PY: 'Python',
  SCR: 'Script',
  SOFT: 'Software',
};

window.PROJECT_CONFIG = {
  paths: {
    [CAT.DEV]: '../assets/images/dev/',
    [CAT.DES]: '../assets/images/design/',
    [CAT.ART]: '../assets/images/ilustraciones/',
    [CAT.VID]: '../assets/images/video/', // Opcional
    DEFAULT: '../assets/images/',
  },
};

/* ========================================================================
   1. PORTAFOLIO PRINCIPAL (DEV + DESIGN + VIDEO)
   ======================================================================== */
window.mainPortfolio = [
  {
    title: 'Gestor local de portafolio',
    fileName: 'https://raw.githubusercontent.com/Tarquitet/portfolio-updater/main/images/README/1769443128324.png',
    link: 'https://github.com/Tarquitet/portfolio-updater',
    desc: 'Script en Python que automatiza la actualización del portafolio sincronizando activos locales y entradas README; reduce el trabajo manual.',
    tools: [T.PY, T.SCR, T.SOFT, T.COM],
    category: CAT.DEV,
    context: CTX.PERS,
    pdfOnly: false,
  },
  {
    title: 'Orquestador de construcción y gestión',
    fileName: 'https://raw.githubusercontent.com/Tarquitet/web-portfolio-manager/main/images/README/1769443877856.png',
    link: 'https://github.com/Tarquitet/web-portfolio-manager',
    desc: 'Orquesta traducción, minificación y actualización del portafolio para agilizar despliegues y reducir pasos manuales.',
    tools: [T.PY, T.SCR, T.SOFT, T.COM],
    category: CAT.DEV,
    context: CTX.PERS,
    pdfOnly: false,
  },
  {
    title: 'Convertidor y compresor OGG',
    fileName: 'https://raw.githubusercontent.com/Tarquitet/ogg-convertor/main/images/README/1769445521124.png',
    link: 'https://github.com/Tarquitet/ogg-convertor',
    desc: 'Convierte y comprime audio por lotes a OGG para ahorrar ancho de banda y espacio de almacenamiento.',
    tools: [T.PY, T.SCR, T.SOFT, T.COM],
    category: CAT.DEV,
    context: CTX.PERS,
    pdfOnly: false,
  },
  {
    title: 'Convertidor HTML a PDF',
    fileName: 'https://raw.githubusercontent.com/Tarquitet/html-2-pdf/main/images/README/1769443738317.png',
    link: 'https://github.com/Tarquitet/html-2-pdf',
    desc: 'Utilidad en Python que convierte páginas HTML a PDFs de alta calidad mediante plantillas configurables.',
    tools: [T.PY, T.SCR, T.SOFT, T.COM],
    category: CAT.DEV,
    context: CTX.PERS,
    pdfOnly: false,
  },
  {
    title: 'Compresor de imágenes offline',
    fileName: 'https://raw.githubusercontent.com/Tarquitet/image-conversor/main/images/README/1769206951282.avif',
    link: 'https://github.com/Tarquitet/image-conversor',
    desc: 'Herramienta de escritorio para optimizar imágenes por lotes, reduciendo tamaños manteniendo la calidad visual.',
    tools: [T.PY, T.SCR, T.SOFT, T.COM],
    category: CAT.DEV,
    context: CTX.PERS,
    pdfOnly: false,
  },
  {
    title: 'Conversor de UUIDs de Minecraft',
    fileName:
      'https://raw.githubusercontent.com/Tarquitet/minecraft_uuid_converter/refs/heads/main/images/README/1769448117738.png',
    link: 'https://github.com/Tarquitet/minecraft_uuid_converter.git',
    desc: 'Utilidad en Python para resolver y gestionar UUIDs de jugadores en distintos sistemas de autenticación.',
    tools: [T.PY, T.SCR, T.SOFT, T.COM],
    category: CAT.DEV,
    context: CTX.PERS,
    pdfOnly: false,
  },
  {
    title: 'Auto-traductor JSON (i18n)',
    category: CAT.DEV,
    context: CTX.PERS,
    fileName: 'https://raw.githubusercontent.com/Tarquitet/web-translator/main/images/README/1769442012384.png',
    link: 'https://github.com/Tarquitet/web-translator',
    desc: 'Automatiza la localización de archivos JSON de texto plano con procesamiento por lotes y backends de traducción configurables.',
    tools: [T.PY, T.SCR, T.SOFT, T.COM],
    pdfOnly: false,
  },
  {
    title: 'Optimizador de activos (minificador CSS/JS)',
    category: CAT.DEV,
    context: CTX.PERS,
    fileName: 'minify-py.avif',
    link: 'https://github.com/Tarquitet/minify-asset-optimizer',
    desc: 'Minifica y normaliza CSS/JS para reducir el tamaño de los paquetes y corregir problemas comunes de minificación.',
    tools: [T.PY, T.SCR, T.SOFT, T.COM],
    pdfOnly: false,
  },
  {
    title: 'Invitación de boda (encargo)',
    category: CAT.DES,
    context: CTX.PERS,
    fileName: 'boda_hermano_1_persona.webp',
    link: '=',
    desc: 'Encargo de cliente: diseño de invitación de boda con ajustes personalizados; entregables listos para impresión.',
    tools: [T.PHOTO],
    pdfOnly: false,
  },
  {
    title: 'Miniatura: video nostálgico Minecraft',
    fileName: 'Minecraft-en-2010.webp',
    link: '=',
    desc: 'Diseño de miniatura para un vídeo sobre las fases tempranas del desarrollo de Minecraft.',
    tools: [T.PHOTO, T.THUMB, T.VID, T.YT],
    category: CAT.DES,
    context: CTX.PERS,
    pdfOnly: false,
  },
  {
    title: 'Mini edición: invitación Semana Santa',
    link: 'https://youtube.com/shorts/Fgi9CA35Onc?feature=share',
    desc: 'Vídeo corto que presenta el diseño de una invitación para Semana Santa.',
    tools: [T.DAVINCI, T.EDIT, T.VID, T.YT],
    category: CAT.VID,
    context: CTX.PERS,
    pdfOnly: false,
  },
  {
    title: 'Demo RA: modelado 3D',
    link: 'https://youtube.com/shorts/b6hb9cotBcM?feature=share',
    desc: 'Demostración de modelado 3D en Realidad Aumentada utilizando Autodesk Maya y Unity.',
    tools: [T.MAYA, T.UNITY, T.VID, T.YT],
    category: CAT.VID,
    context: CTX.UNIV,
    pdfOnly: false,
  },
  {
    title: 'Overlay de cierre para streaming',
    category: CAT.DES,
    context: CTX.PERS,
    fileName: 'Fondo-offline-v1.avif',
    link: 'https://www.twitch.tv/tarquitet',
    desc: 'Diseño de overlay para transmisiones en directo (Twitch/YouTube); entregables en PNG y PSD.',
    tools: [T.PHOTO, T.TW, T.VID, T.YT],
    pdfOnly: false,
  },
  {
    title: 'Logo G.O.U.G',
    category: CAT.DES,
    context: CTX.PERS,
    fileName: 'GOUG-logo.webp',
    link: 'https://www.curseforge.com/minecraft/modpacks/goug-optimized',
    desc: 'Diseño de logotipo para el modpack G.O.U.G; incluye versiones vectoriales y rasterizadas.',
    tools: [T.PHOTO],
    pdfOnly: false,
  },
  {
    title: 'Anuncio frontal para Iglesia',
    category: CAT.DES,
    context: CTX.PROF,
    fileName: 'anuncio-gold-papa.avif',
    link: '=',
    desc: 'Diseño de anuncio frontal para impresión y exposición en la fachada de una iglesia local.',
    tools: [T.PHOTO],
    pdfOnly: false,
  },
  {
    title: 'Rediseño: Instituto Bíblico Horeb',
    category: CAT.DES,
    context: CTX.PROF,
    fileName: 'IBHOREB-1.avif',
    link: '=',
    desc: 'Rediseño de identidad visual para Instituto Bíblico Horeb, orientado a legibilidad y aplicaciones impresas.',
    tools: [T.PHOTO],
    pdfOnly: false,
  },
  {
    title: 'Anuncio frontal (Iglesia)',
    category: CAT.DES,
    context: CTX.PROF,
    fileName: 'IUJ-GLORIA.webp',
    link: '=',
    desc: 'Diseño de anuncio frontal para impresión y exposición en la fachada de una iglesia local.',
    tools: [T.PHOTO],
    pdfOnly: false,
  },
  {
    title: 'Miniatura: instalación de modpack',
    category: CAT.DES,
    context: CTX.PERS,
    fileName: 'NostalgiCraft-Modpack.webp',
    link: '=',
    desc: 'Miniatura diseñada para un tutorial sobre cómo instalar un modpack en Minecraft.',
    tools: [T.PHOTO, T.THUMB, T.VID, T.YT],
    pdfOnly: false,
  },
  {
    title: 'Maquetación: oferta laboral (ATOM Solutions)',
    category: CAT.DES,
    context: CTX.PROF,
    fileName: 'oferta_laboral_tecnico.webp',
    link: '=',
    desc: 'Maquetación del anuncio de empleo para ATOM Solutions; entregables listos para web e impresión.',
    tools: [T.PHOTO],
    pdfOnly: false,
  },
  {
    title: 'Edición de fotograma — Cities in Dust',
    category: CAT.DES,
    context: CTX.UNIV,
    fileName: 'Edicion_Fotograma_CitiesInDust.avif',
    link: '=',
    desc: 'Edición rápida (≤1 h) de un fotograma del videoclip musical para un proyecto académico.',
    tools: [T.PHOTO, T.VID],
    pdfOnly: false,
  },
  {
    title: 'Render final — cómic (universidad)',
    category: CAT.DES,
    context: CTX.PERS,
    fileName: 'preview-comic-render.webp',
    link: '/assets/pdf/university/DavidPinto_ComicFinal_Unido_compressed.pdf',
    desc: 'Render final de un cómic realizado de forma individual para la asignatura de Render.',
    tools: [T.MAYA, T.PHOTO],
    pdfOnly: false,
  },
  {
    title: 'Propuesta mockup — Día Multimedia',
    category: CAT.DES,
    context: CTX.UNIV,
    fileName: 'smartmockups_l7w4oeot.avif',
    link: '=',
    desc: 'Propuesta de logo y mockup para el Día del Ingeniero Multimedia; incluye presentaciones y mockups de aplicación.',
    tools: [T.ILUS, T.PHOTO],
    pdfOnly: false,
  },
  {
    title: 'Retro CGI Art #02',
    category: CAT.DES,
    context: CTX.PERS,
    fileName: 'test_2.webp',
    link: '=',
    desc: 'Obra CGI inspirada en estética retro previa a los años 2000.',
    tools: [T.MAYA, T.PHOTO],
    pdfOnly: false,
  },
  {
    title: 'Retro CGI Art #01',
    category: CAT.DES,
    context: CTX.PERS,
    fileName: 'test_3.webp',
    link: '=',
    desc: 'Obra CGI inspirada en estética retro previa a los años 2000.',
    tools: [T.MAYA, T.PHOTO],
    pdfOnly: false,
  },
  {
    title: 'Logo Fancy Land',
    category: CAT.DES,
    context: CTX.PERS,
    fileName: 'Texto-Fancy-Land.avif',
    link: '=',
    desc: 'Diseño de logotipo para una serie de Minecraft; incluye archivos escalables.',
    tools: [T.PHOTO],
    pdfOnly: false,
  },
  {
    title: 'Los sueños hechos realidad',
    category: CAT.DES,
    context: CTX.UNIV,
    fileName: 'Transmedia - composicion narrativa - Montaje Final - David Pinto.webp',
    link: '=',
    desc: 'Diseño conceptual sobre la expresión de un mundo onírico en formato visual.',
    tools: [T.PHOTO],
    pdfOnly: false,
  },
  {
    title: 'Diseño de niveles (Unreal Engine)',
    category: CAT.DEV,
    context: CTX.UNIV,
    fileName: 'unreal5.avif',
    link: '=',
    desc: 'Diseño de iluminación y niveles para un proyecto académico en Unreal Engine.',
    tools: [T.CS, T.UNREAL],
    pdfOnly: false,
  },
  {
    title: 'Rediseño logo — Verdad & Fe',
    category: CAT.DES,
    context: CTX.PROF,
    fileName: 'V&F-6.avif',
    link: 'https://www.verdadyfe.org/',
    desc: 'Rediseño de identidad visual para el ministerio Verdad & Fe; preparado para web e impresión.',
    tools: [T.PHOTO],
    pdfOnly: false,
  },
  {
    title: 'Miniatura: Parkour Minecraft',
    category: CAT.DES,
    context: CTX.PERS,
    fileName: '200-Parkours---reto-1.webp',
    link: '=',
    desc: 'Diseño de miniatura para un vídeo de parkour en Minecraft.',
    tools: [T.PHOTO, T.THUMB, T.VID, T.YT],
    pdfOnly: false,
  },
  {
    title: 'Sitio web ministerial — Verdad & Fe',
    category: CAT.DEV,
    context: CTX.PROF,
    fileName: 'verdadyfe.avif',
    link: 'https://www.verdadyfe.org/',
    desc: 'Landing page oficial desarrollada con HTML/CSS/JS para el ministerio Verdad & Fe.',
    tools: [T.HTML, T.CSS, T.JS, T.FRONT, 'SEO'],
    pdfOnly: false,
  },
  {
    title: 'Sitio oficial — Tarquitet',
    category: CAT.DEV,
    context: CTX.PROF,
    fileName: 'tarquitet-site.avif',
    link: '#',
    desc: 'Sitio personal de portafolio con diseño responsive y visualización de proyectos.',
    tools: [T.HTML, T.CSS, T.JS, 'Portfolio', T.FRONT, 'Web Design', 'Backend'],
    pdfOnly: false,
  },
  {
    title: 'Tarquitet (versión anterior)',
    category: CAT.DEV,
    context: CTX.PROF,
    fileName: 'tarquitet-old-site.avif',
    link: '/ver1/index.html',
    desc: 'Versión previa del sitio de portafolio (archivada).',
    tools: [T.HTML, T.CSS, T.JS, 'Portfolio', T.FRONT, 'Web Design', 'Backend'],
    pdfOnly: false,
  },
  {
    title: 'Builtechraft Web (1st ver)',
    category: CAT.DEV,
    context: CTX.UNIV,
    fileName: 'Builtechraft-web-2024.avif',
    link: 'https://tarquitet.github.io/Builtechraft-Web/',
    desc: 'Sitio web para proyecto de servidor multijugador; incluye presentación del proyecto y detalles del servidor.',
    tools: [T.HTML, T.CSS, T.JS, T.FRONT, 'Web Design', 'Minecraft', T.WEB],
    pdfOnly: false,
  },
  {
    title: 'Builtechraft Web',
    category: CAT.DEV,
    context: CTX.PROF,
    fileName: 'btc-2026.avif',
    link: 'https://builtechraft.tarquitet.com/',
    desc: 'Sitio web para proyecto de servidor multijugador; incluye presentación del proyecto y detalles del servidor.',
    tools: [T.HTML, T.CSS, T.JS, T.FRONT, 'Web Design', 'Minecraft', T.WEB],
    pdfOnly: false,
  },
  {
    title: 'Instituto Bíblico Horeb Web',
    category: CAT.DEV,
    context: CTX.PROF,
    fileName: 'instituto-web.avif',
    link: 'https://pagina-instituto.pages.dev/',
    desc: 'Sitio web para el instituto bíblico; incluye presentación del instituto, programas académicos y contacto.',
    tools: ['Academic', T.HTML, T.CSS, T.JS, T.FRONT, 'Web Design', T.WEB],
    pdfOnly: false,
  },
  {
    title: 'App Gimnasio 3D Virtual',
    desc: 'Aplicación móvil con demos en 360° y explicaciones biomecánicas; prototipo de UI incluido.',
    fileName:
      'https://raw.githubusercontent.com/pintomultimedia2002/GymApp_1_2024/refs/heads/main/Assets/prototipo-demo.png',
    link: 'https://github.com/pintomultimedia2002/GymApp_1_2024',
    tools: [T.UNITY, T.CS, 'UI Mobile'],
    category: CAT.DEV,
    context: CTX.UNIV,
    pdfOnly: false,
  },
  {
    title: 'Solver inteligente de Sudoku',
    desc: 'Generador y solucionador de Sudokus mediante backtracking optimizado; prototipo de investigación.',
    fileName:
      'https://raw.githubusercontent.com/pintomultimedia2002/Sudoku_Intelligent_Backtracking/refs/heads/master/sudokugenerado.png',
    link: 'https://github.com/pintomultimedia2002/Sudoku_Intelligent_Backtracking',
    tools: [T.CS, 'Backtracking', 'IA'],
    category: CAT.DEV,
    context: CTX.UNIV,
    pdfOnly: false,
  },
  {
    title: 'C.I.P.S Puzzle Solver',
    desc: 'Mini-juego experimental de IA que resuelve puzzles numéricos mediante heurísticas.',
    fileName:
      'https://raw.githubusercontent.com/pintomultimedia2002/CIPS_Intelligent_Puzzle_Solver/refs/heads/master/puzzle-solved.jpg',
    link: 'https://github.com/pintomultimedia2002/CIPS_Intelligent_Puzzle_Solver',
    tools: [T.CS, 'Heurística', 'IA'],
    category: CAT.DEV,
    context: CTX.UNIV,
    pdfOnly: false,
  },
  {
    title: 'Agente Wumpus World',
    desc: 'Simulación de un agente racional basada en lógica proposicional para toma de decisiones.',
    fileName:
      'https://raw.githubusercontent.com/pintomultimedia2002/wumpus-world-javascript/refs/heads/main/src/resources/wampus.png',
    link: 'https://github.com/pintomultimedia2002/wumpus-world-javascript',
    tools: [T.JS, 'Lógica', 'IA Clásica'],
    category: CAT.DEV,
    context: CTX.UNIV,
    pdfOnly: false,
  },
  {
    title: 'Algoritmo A* (pathfinding)',
    desc: 'Implementación del algoritmo A* para búsqueda de caminos óptimos; incluye demo visual.',
    fileName:
      'https://raw.githubusercontent.com/pintomultimedia2002/A_star_algorithm_Javascript/refs/heads/main/wampus-ia.png',
    link: 'https://github.com/pintomultimedia2002/A_star_algorithm_Javascript',
    tools: [T.JS, 'Pathfinding', 'Algoritmos'],
    category: CAT.DEV,
    context: CTX.UNIV,
    pdfOnly: false,
  },
  {
    title: 'Asistente CarVoice',
    desc: 'Asistente por voz para entornos vehiculares con prototipo de interfaz web e integraciones.',
    fileName:
      'https://raw.githubusercontent.com/pintomultimedia2002/carvoice-assist/refs/heads/main/assets/asistant-2.png',
    link: 'https://github.com/pintomultimedia2002/carvoice-assist',
    tools: [T.HTML, T.CSS, T.JS, T.FRONT, 'Web Design', 'Voiceflow', 'Chatbot', T.WEB],
    category: CAT.DEV,
    context: CTX.UNIV,
    pdfOnly: false,
  },
  {
    title: 'Algebrain App',
    desc: 'Aplicación educativa de álgebra centrada en UX; ejercicios interactivos y seguimiento de progreso.',
    fileName:
      'https://raw.githubusercontent.com/pintomultimedia2002/Algebrain-App/refs/heads/main/resources/images/algebrain-demo-4.png',
    link: 'https://github.com/pintomultimedia2002/Algebrain-App',
    tools: [T.HTML, T.CSS, T.JS, T.FRONT, 'Web Design', 'eLearning', 'Web App', 'Mobile', T.WEB],
    category: CAT.DEV,
    context: CTX.UNIV,
    pdfOnly: false,
  },
  {
    title: 'Experiencia VR 360°',
    category: CAT.DEV,
    context: CTX.UNIV,
    fileName: 'audio-video-360.avif',
    link: 'https://www.youtube.com/watch?v=Z8sgOhYMAl4',
    desc: 'Experiencia inmersiva de terror en VR creada en Unity con audio 3D e elementos interactivos.',
    tools: [T.UNITY, 'VR', 'Audio 3D', T.CS, 'Immersiva', '360°', 'Video', 'Audio', 'XR'],
    pdfOnly: false,
  },
  {
    title: 'Simulación 3D OpenGL',
    category: CAT.DEV,
    context: CTX.UNIV,
    fileName: 'unity-opengl-web.avif',
    link: 'https://relaxed-valkyrie-75101a.netlify.app/',
    desc: 'Minijuego de recolección con físicas básicas, implementado para despliegue WebGL.',
    tools: [T.UNITY, 'Simulación', '3D', 'Físicas', 'WebGL', T.WEB, T.CS],
    pdfOnly: false,
  },
  {
    title: 'Sonórus — Rediseño UI',
    category: CAT.DES,
    context: CTX.UNIV,
    fileName: 'Sonorus-Figma.avif',
    link: 'https://www.figma.com/design/lClUfMJDAuqfEhvXN6IN2B/Untitled?node-id=0-1&t=UD8TxB4UupRydWWD-1',
    desc: 'Rediseño de interfaz para aplicación musical; prototipos en Figma y kit de UI.',
    tools: [T.FIGMA, 'UI Design', 'Prototyping', 'Redesign', T.UI, T.UX, 'Mobile Design'],
    pdfOnly: false,
  },
  {
    title: '4 Better Pets — App móvil',
    category: CAT.DES,
    context: CTX.UNIV,
    fileName: '4better-pets-app.avif',
    link: 'https://www.figma.com/design/8LDG3cejNOO7Re9Z6MMrfU/4-BETTER-PETS?node-id=0-1&t=fkQtYiNLOuIEM5Uo-1',
    desc: 'Prototipo móvil para facilitar la adopción de mascotas; incluye investigación UX y prototipos.',
    tools: [T.FIGMA, 'UX Research', 'Mobile Design', 'Prototyping', T.UI, T.UX, 'App Design'],
    pdfOnly: false,
  },
  {
    title: 'Rediseño UI — Rappi',
    category: CAT.DES,
    context: CTX.UNIV,
    fileName: 'RedisenoRappi-Figma.avif',
    link: 'https://www.figma.com/design/W8tY2RtS3hM7B9BQjJgpiB/David-Pinto---Redise%C3%B1o-Rappi?node-id=0-1&t=UmSvMcQEsiyU7y4s-1',
    desc: 'Propuesta de rediseño centrada en mejorar la experiencia de usuario y la consistencia visual.',
    tools: [T.FIGMA, 'UI Kit', 'Redesign', T.UI, T.UX, 'App Design'],
    pdfOnly: false,
  },
  {
    title: 'In-Mortal Transmedia',
    desc: 'Exploración narrativa transmedia sobre la evolución de las ideas; sitio del proyecto y activos narrativos.',
    fileName: 'in-mortal.avif',
    link: 'https://pintodavid2002.wixsite.com/in-mortal',
    tools: ['Storytelling', 'Wix', 'Concept Art', 'Narrative', 'Transmedia', 'Web Design', T.WEB, T.UX],
    category: CAT.DEV,
    context: CTX.PERS,
    pdfOnly: false,
  },
  {
    title: 'Planty — Video instruccional',
    date: '2023-05-20',
    channel: 'CLIENTE',
    link: 'https://www.youtube.com/watch?v=1AMhkDXVkqU',
    desc: 'Video instruccional para Planty (cliente); incluye guía paso a paso.',
    category: CAT.VID,
    context: CTX.UNIV,
    pdfOnly: false,
  },
  {
    title: 'Planty — Detrás de cámaras',
    date: '2023-05-25',
    channel: 'CLIENTE',
    link: 'https://www.youtube.com/watch?v=scgv4lL-4vk',
    desc: 'Material detrás de cámaras de la producción de Planty.',
    category: CAT.VID,
    context: CTX.UNIV,
    pdfOnly: false,
  },
  {
    title: 'Iglesia Misionera Antioquia — Evento',
    date: '2021-07-15',
    channel: 'CLIENTE',
    link: 'https://www.youtube.com/watch?v=zi_l5z1Yx6s',
    desc: 'Registro y edición de evento para Iglesia Misionera Antioquia (cliente).',
    category: CAT.VID,
    context: CTX.PERS,
    pdfOnly: false,
  },
  {
    title: 'Trailer — Algebrain',
    date: '2024-02-10',
    channel: 'PROMO',
    link: 'https://www.youtube.com/watch?v=9rP3nJe5S4g',
    desc: 'Tráiler promocional de la aplicación Algebrain mostrando funcionalidades y UI.',
    category: CAT.VID,
    context: CTX.UNIV,
    pdfOnly: false,
  },
  {
    title: 'Comercial parodia — GymApp',
    date: '2024-01-15',
    channel: 'COMERCIAL',
    link: 'https://www.youtube.com/watch?v=QWK7JctMbug',
    desc: 'Comercial parodia creado como pieza promocional para GymApp.',
    category: CAT.VID,
    context: CTX.UNIV,
    pdfOnly: false,
  },
  {
    title: 'Radionovela — Suspenso',
    date: '2023-06-10',
    channel: 'ARCHIVO',
    link: 'https://www.youtube.com/watch?v=VJC3mEY-dFU',
    desc: 'Producción de radionovela en género de suspenso (archivo).',
    category: CAT.VID,
    context: CTX.UNIV,
    pdfOnly: false,
  },
  {
    title: 'Minidocumental — Arte electrónico',
    date: '2022-11-10',
    channel: 'DOCU',
    link: 'https://www.youtube.com/watch?v=P4X0pvVxqVE',
    desc: 'Minidocumental sobre prácticas de arte electrónico.',
    category: CAT.VID,
    context: CTX.UNIV,
    pdfOnly: false,
  },
  {
    title: 'Brainstorming — Proyecto Brock',
    date: '2022-09-05',
    channel: 'ARCHIVO',
    link: 'https://www.youtube.com/watch?v=ijmfr-FB1dM',
    desc: 'Sesión de brainstorming y material de prototipo (archivo).',
    category: CAT.VID,
    context: CTX.UNIV,
    pdfOnly: false,
  },
  {
    title: 'Stop motion — Pixelation',
    date: '2022-04-15',
    channel: 'ANIMACIÓN',
    link: 'https://www.youtube.com/watch?v=ui06UdetAPg',
    desc: 'Proyecto de animación stop-motion usando técnicas de pixelation.',
    category: CAT.VID,
    context: CTX.UNIV,
    pdfOnly: false,
  },
  {
    title: 'Narrativa visual — Ética',
    date: '2020-08-20',
    channel: 'ARCHIVO',
    link: 'https://www.youtube.com/watch?v=DR1FwQc-9rQ',
    desc: 'Proyecto académico sobre narrativa visual y temas éticos.',
    context: CTX.UNIV,
    category: CAT.VID,
    pdfOnly: false,
  },
  {
    title: 'Render sincronizado 3D',
    date: '2023-11-15',
    channel: 'ARCHIVO',
    link: 'https://www.youtube.com/watch?v=VcCDOt0Uujk',
    desc: 'Render 3D sincronizado con animación (archivo).',
    category: CAT.VID,
    context: CTX.UNIV,
    pdfOnly: false,
  },
  {
    title: 'Saco animado 3D',
    date: '2023-10-20',
    channel: 'ARCHIVO',
    link: 'https://www.youtube.com/watch?v=wKekfdNC3ZY',
    desc: 'Cortometraje/animación 3D protagonizado por un personaje tipo saco (archivo).',
    category: CAT.VID,
    context: CTX.UNIV,
    pdfOnly: false,
  },
  {
    title: 'Playblast — Electro Swing',
    date: '2023-09-05',
    channel: 'ARCHIVO',
    link: 'https://youtu.be/v3VPVmA7qOs',
    desc: 'Playblast de animación para proyecto musical (archivo).',
    category: CAT.VID,
    context: CTX.UNIV,
    pdfOnly: false,
  },
  {
    title: 'Playblast & edit — Cops',
    date: '2023-08-15',
    channel: 'ARCHIVO',
    link: 'https://youtu.be/V3ABRvOuce0',
    desc: 'Compilación de playblasts y edición para proyecto Cops (archivo).',
    category: CAT.VID,
    context: CTX.UNIV,
    pdfOnly: false,
  },
  {
    title: 'Timelapse — Desarrollo GymApp',
    date: '2024-01-20',
    channel: 'DEVLOG',
    link: 'https://www.youtube.com/watch?v=ANcyGAwcUac',
    desc: 'Timelapse del proceso de desarrollo del prototipo GymApp.',
    category: CAT.VID,
    context: CTX.UNIV,
    pdfOnly: false,
  },
  {
    title: 'Dibujo digital — Mis inicios',
    date: '2022-03-20',
    channel: 'ARTE',
    link: 'https://www.youtube.com/watch?v=QV04Wh2BU0E',
    desc: 'Serie de dibujos digitales tempranos que muestran la evolución personal.',
    category: CAT.VID,
    context: CTX.UNIV,
    pdfOnly: false,
  },
  {
    title: 'Tutorial — POO en Java',
    date: '2020-05-15',
    channel: 'TUTORIAL',
    link: 'https://www.youtube.com/watch?v=qIxRbcXezWU',
    desc: 'Tutorial sobre programación orientada a objetos en Java.',
    category: CAT.VID,
    context: CTX.UNIV,
    pdfOnly: false,
  },
];

/* ========================================================================
   2. GALERÍA VISUAL (ARTE)
   ======================================================================== */
window.galleryData = [];
