/* ========================================================================
   OPTIMIZACIÓN DE TAXONOMÍA (Ahorro de bytes y consistencia)
   ======================================================================== */
window.CTX = {
  PROF: 'PROFESSIONAL',
  UNIV: 'UNIVERSITY',
  PERS: 'PERSONAL',
};

window.CAT = {
  DEV: 'DEV',
  DES: 'DESIGN',
  VID: 'VIDEO',
  ART: 'ART',
};

// Herramientas más repetidas (Opcional, pero ayuda mucho a reducir peso)
window.T = {
  HTML: 'HTML',
  CSS: 'CSS',
  JS: 'Javascript',
  CS: 'C#',
  UNITY: 'Unity',
  FIGMA: 'Figma',
  WEB: 'Web',
  FRONT: 'Frontend',
  UI: 'UI',
  UX: 'UX',
  PHOTO: 'Photoshop',
  ILUS: 'Ilustrator',
  UNREAL: 'Unreal Engine',
  MAYA: 'Autodesk Maya',
  DAVINCI: 'DaVinci Resolve',
  EDIT: 'Edición de Video',
  VID: 'Video',
  YT: 'YouTube',
  THUMB: 'Miniaturas',
  TW: 'Twitch',
  COM: 'Comunitario',
  PY: 'Python',
  SCR: 'Script',
  SOFT: 'Software',
};

window.PROJECT_CONFIG = {
  paths: {
    [CAT.DEV]: '../assets/images/dev/',
    [CAT.DES]: '../assets/images/design/',
    [CAT.ART]: '../assets/images/ilustraciones/',
    [CAT.VID]: '../assets/images/video/', // Opcional
    DEFAULT: '../assets/images/',
  },
};

/* ========================================================================
   1. PORTAFOLIO PRINCIPAL (DEV + DESIGN + VIDEO)
   ======================================================================== */
window.mainPortfolio = [
  {
    title: 'Universal Portfolio Local DB Manager',
    fileName: 'https://raw.githubusercontent.com/Tarquitet/portfolio-updater/main/images/README/1769443128324.png',
    link: 'https://github.com/Tarquitet/portfolio-updater',
    desc: 'Helper for updating my profile website automated',
    tools: [T.PY, T.SCR, T.SOFT, T.COM],
    category: CAT.DEV,
    context: CTX.PERS,
  },
  {
    title: 'Project Manager & Build Orchestrator',
    fileName: 'https://raw.githubusercontent.com/Tarquitet/web-portfolio-manager/main/images/README/1769443877856.png',
    link: 'https://github.com/Tarquitet/web-portfolio-manager',
    desc: 'Automated helper (translator + minify + portfolio updater) for my official website',
    tools: [T.PY, T.SCR, T.SOFT, T.COM],
    category: CAT.DEV,
    context: CTX.PERS,
  },
  {
    title: 'JSON Auto-Translator (i18n Tool)',
    category: CAT.DEV,
    context: CTX.PERS,
    fileName: 'translator-py.avif',
    link: 'https://github.com/Tarquitet/web-translator',
    desc: 'Auto-translator for every kinda of plain text files if you need to automate your process updating your web site text files into another lang',
    tools: [T.PY, T.SCR, T.SOFT, T.COM],
  },
  {
    title: 'Asset Optimizer (CSS/JS Minifier)',
    category: CAT.DEV,
    context: CTX.PERS,
    fileName: 'minify-py.avif',
    link: 'https://github.com/Tarquitet/minify-asset-optimizer',
    desc: 'This script helps you fixing some errors using minify like deleting unnecessary lists, break lines, some spaces to identify other objects.',
    tools: [T.PY, T.SCR, T.SOFT, T.COM],
  },
  {
    title: 'OGG CONVERTER/COMPRESSOR',
    fileName: 'https://raw.githubusercontent.com/Tarquitet/ogg-convertor/main/images/README/1769445521124.png',
    link: 'https://github.com/Tarquitet/ogg-convertor',
    desc: 'Bro, why do you need to download more than 1GB on audio when you can compress those files a little more to save time and space?',
    tools: [T.PY, T.SCR, T.SOFT, T.COM],
    category: CAT.DEV,
    context: CTX.PERS,
  },
  {
    title: 'HTML 2 PDF',
    fileName: 'https://raw.githubusercontent.com/Tarquitet/html-2-pdf/main/images/README/1769443738317.png',
    link: 'https://github.com/Tarquitet/html-2-pdf',
    desc: 'Simple python program to convert html 2 pdf.',
    tools: [T.PY, T.SCR, T.SOFT, T.COM],
    category: CAT.DEV,
    context: CTX.PERS,
  },
  {
    title: 'Offline Image Compressor',
    fileName: 'https://raw.githubusercontent.com/Tarquitet/image-conversor/main/images/README/1769206951282.avif',
    link: 'https://github.com/Tarquitet/image-conversor',
    desc: 'This project was made to optimize some images for my personal website. Of course, there are so many websites that can do the same thing, but- You need to pay for more. So. Why not trying myself?',
    tools: [T.PY, T.SCR, T.SOFT, T.COM],
    category: CAT.DEV,
    context: CTX.PERS,
  },
  {
    title: 'Minecraft UUID Converter',
    fileName: 'https://raw.githubusercontent.com/Tarquitet/minecraft_uuid_converter/refs/heads/main/images/README/1769448117738.png',
    link: 'https://github.com/Tarquitet/minecraft_uuid_converter.git',
    desc: 'Python program that allows to renaming uuid players files or finding uuids from mojang, elyby, offline auth',
    tools: [T.PY, T.SCR, T.SOFT, T.COM],
    category: CAT.DEV,
    context: CTX.PERS,
  },
  {
    title: 'wedding invitation',
    category: CAT.DES,
    context: CTX.PERS,
    fileName: 'boda_hermano_1_persona.webp',
    link: '=',
    desc: 'The client had requested a similar design that he had found online with slight changes. Here is the complete work.',
    tools: [T.PHOTO, T.THUMB, T.VID, T.YT],
  },
  {
    title: 'Thumbnail for nostalgic Minecraft video',
    fileName: 'Minecraft-en-2010.webp',
    link: '=',
    desc: 'Design for a miniature about the early phases of the development of the Minecraft video game',
    tools: [T.PHOTO, T.THUMB, T.VID, T.YT],
    category: CAT.DES,
    context: CTX.PERS,
  },
  {
    title: 'Mini-edit: Easter Invitation',
    link: 'https://youtube.com/shorts/Fgi9CA35Onc?feature=share',
    desc: 'Short video about an invitation for Easter',
    tools: [T.DAVINCI, T.EDIT, T.VID, T.YT],
    category: CAT.VID,
    context: CTX.PERS,
  },
  {
    title: 'Sample Augmented Reality 3D Modeling',
    link: 'https://youtube.com/shorts/b6hb9cotBcM?feature=share',
    desc: 'Sample 3D Modeling in Augmented Reality using Maya and unity',
    tools: [T.MAYA, T.UNITY, T.VID, T.YT],
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Ending overlay for Twitch',
    category: CAT.DES,
    context: CTX.PERS,
    fileName: 'Fondo-offline-v1.avif',
    link: 'https://www.twitch.tv/tarquitet',
    desc: 'Design for an overlay for live shows on platforms like Youtube or Twitch',
    tools: [T.PHOTO, T.TW, T.VID, T.YT],
  },
  {
    title: 'G.O.U.G Logo',
    category: CAT.DES,
    context: CTX.PERS,
    fileName: 'GOUG-logo.webp',
    link: 'https://www.curseforge.com/minecraft/modpacks/goug-optimized',
    desc: 'Logo for the minecraft G.O.U.G modpack',
    tools: [T.PHOTO],
  },
  {
    title: 'Logo Redesign - Instituto Biblico',
    category: CAT.DES,
    context: CTX.PROF,
    fileName: 'IBHOREB-1.avif',
    link: '=',
    desc: 'Redesign for the logo of the Horeb Bible Institute',
    tools: [T.PHOTO],
  },
  {
    title: 'Front advertisement - Church',
    category: CAT.DES,
    context: CTX.PROF,
    fileName: 'IUJ-GLORIA.webp',
    link: '=',
    desc: 'Front advertisement to be printed and displayed in front of a local church',
    tools: [T.PHOTO],
  },
  {
    title: 'Thumbnail on how to install a modpack in Minecraft',
    category: CAT.DES,
    context: CTX.PERS,
    fileName: 'NostalgiCraft-Modpack.webp',
    link: '=',
    desc: 'Design for a miniature for an exploration modpack in Minecraft',
    tools: [T.PHOTO, T.THUMB, T.VID, T.YT],
  },
  {
    title: 'Layout of job offer ATOM Solutions S.A.S',
    category: CAT.DES,
    context: CTX.PROF,
    fileName: 'oferta_laboral_tecnico.webp',
    link: '=',
    desc: 'Layout Design for a job offer from ATOMS Solutions',
    tools: [T.PHOTO],
  },
  {
    title: 'Edit Cities in Dust song frame',
    category: CAT.DES,
    context: CTX.UNIV,
    fileName: 'Edicion_Fotograma_CitiesInDust.avif',
    link: '=',
    desc: 'Quick editing in less than 1 hour on a frame from the Cities in Dust music video',
    tools: [T.PHOTO, T.VID],
  },
  {
    title: 'Comic Final Subject Render - University',
    category: CAT.DES,
    context: CTX.PERS,
    fileName: 'preview-comic-render.webp',
    link: '=',
    desc: 'Final render of a comic made individually for the Rendering subject at the university',
    tools: [T.MAYA, T.PHOTO],
  },
  {
    title: 'Multiemdia Day Mockup Proposal',
    category: CAT.DES,
    context: CTX.UNIV,
    fileName: 'smartmockups_l7w4oeot.avif',
    link: '=',
    desc: 'Proposal for a logo with its respective mockup for the multimedia engineer\'s day in 2022',
    tools: [T.ILUS, T.PHOTO],
  },
  {
    title: 'Retro CGI Art #02',
    category: CAT.DES,
    context: CTX.PERS,
    fileName: 'test_2.webp',
    link: '=',
    desc: 'Second design inspired by Retro CGI from before 2000',
    tools: [T.MAYA, T.PHOTO],
  },
  {
    title: 'Retro CGI Art #01',
    category: CAT.DES,
    context: CTX.PERS,
    fileName: 'test_3.webp',
    link: '=',
    desc: 'First design inspired by Retro CGI from before 2000',
    tools: [T.MAYA, T.PHOTO],
  },
  {
    title: 'Fancy Land Logo',
    category: CAT.DES,
    context: CTX.PERS,
    fileName: 'Texto-Fancy-Land.avif',
    link: '=',
    desc: 'Logo design for a Minecraft series',
    tools: [T.PHOTO],
  },
  {
    title: 'Dreams come true',
    category: CAT.DES,
    context: CTX.UNIV,
    fileName: 'Transmedia - composicion narrativa - Montaje Final - David Pinto.webp',
    link: '=',
    desc: 'Design about the expression of a dream world in reality',
    tools: [T.PHOTO],
  },
  {
    title: 'Level design with Unreal Engine',
    category: CAT.DEV,
    context: CTX.UNIV,
    fileName: 'unreal5.avif',
    link: '=',
    desc: 'Design of lights and levels for a diploma project',
    tools: [T.CS, T.UNREAL],
  },
  {
    title: 'Logo design for Truth & Faith Ministry',
    category: CAT.DES,
    context: CTX.PROF,
    fileName: 'V&F-6.avif',
    link: 'https://www.verdadyfe.org/',
    desc: 'Logo redesign for the Truth & Faith ministry',
    tools: [T.PHOTO],
  },
  {
    title: 'Parkour in Minecraft',
    category: CAT.DES,
    context: CTX.PERS,
    fileName: '200-Parkours---reto-1.webp',
    link: '=',
    desc: 'Thumbnail design about the idea for a Youtube video',
    tools: [T.PHOTO, T.THUMB, T.VID, T.YT],
  },
  {
    title: 'Ministerial Website',
    category: CAT.DEV,
    context: CTX.PROF,
    fileName: 'verdadyfe.avif',
    link: 'https://www.verdadyfe.org/',
    desc: 'Official landing page for the Truth & Faith ministry.',
    tools: [T.HTML, T.CSS, T.JS, T.FRONT, 'SEO'],
  },
  {
    title: 'Tarquitet Official Site',
    category: CAT.DEV,
    context: CTX.PROF,
    fileName: 'tarquitet-site.avif',
    link: '#',
    desc: 'Official website of the Tarquitet portfolio.',
    tools: [T.HTML, T.CSS, T.JS, 'Portfolio', T.FRONT, 'Web Design', 'Backend'],
  },
  {
    title: 'Tarquitet Old Site',
    category: CAT.DEV,
    context: CTX.PROF,
    fileName: 'tarquitet-old-site.avif',
    link: '/ver1/index.html',
    desc: 'Previous web design of the official Tarquitet portfolio.',
    tools: [T.HTML, T.CSS, T.JS, 'Portfolio', T.FRONT, 'Web Design', 'Backend'],
  },
  {
    title: 'Builtechraft Web',
    category: CAT.DEV,
    context: CTX.UNIV,
    fileName: 'Builtechraft-web-2024.avif',
    link: 'https://tarquitet.github.io/Builtechraft-Web/',
    desc: 'Website for a personal project on a multiplayer server.',
    tools: [T.HTML, T.CSS, T.JS, T.FRONT, 'Web Design', 'Minecraft', T.WEB],
  },
  {
    title: '3D Virtual Gym App',
    desc: 'Mobile app with exercises in 360° view and biomechanical explanation.',
    fileName: 'https://raw.githubusercontent.com/pintomultimedia2002/GymApp_1_2024/refs/heads/main/Assets/prototipo-demo.png',
    link: 'https://github.com/pintomultimedia2002/GymApp_1_2024',
    tools: [T.UNITY, T.CS, 'UI Mobile'],
    category: CAT.DEV,
    context: CTX.UNIV,
  },
  {
    title: 'Intelligent Sudoku Solver',
    desc: 'AI that generates and solves Sudokus through efficient Backtracking.',
    fileName: 'https://raw.githubusercontent.com/pintomultimedia2002/Sudoku_Intelligent_Backtracking/refs/heads/master/sudokugenerado.png',
    link: 'https://github.com/pintomultimedia2002/Sudoku_Intelligent_Backtracking',
    tools: [T.CS, 'Backtracking', 'IA'],
    category: CAT.DEV,
    context: CTX.UNIV,
  },
  {
    title: 'C.I.P.S Puzzle Solver',
    desc: 'Minigame about experimental AI that solves numerical puzzles.',
    fileName: 'https://raw.githubusercontent.com/pintomultimedia2002/CIPS_Intelligent_Puzzle_Solver/refs/heads/master/puzzle-solved.jpg',
    link: 'https://github.com/pintomultimedia2002/CIPS_Intelligent_Puzzle_Solver',
    tools: [T.CS, 'Heurística', 'IA'],
    category: CAT.DEV,
    context: CTX.UNIV,
  },
  {
    title: 'Wumpus World Agent',
    desc: 'Simulation of a Rational Agent based on propositional logic.',
    fileName: 'https://raw.githubusercontent.com/pintomultimedia2002/wumpus-world-javascript/refs/heads/main/src/resources/wampus.png',
    link: 'https://github.com/pintomultimedia2002/wumpus-world-javascript',
    tools: [T.JS, 'Lógica', 'IA Clásica'],
    category: CAT.DEV,
    context: CTX.UNIV,
  },
  {
    title: 'A* Pathfinder Algorithm',
    desc: 'Implementation of the A* algorithm for optimal path search.',
    fileName: 'https://raw.githubusercontent.com/pintomultimedia2002/A_star_algorithm_Javascript/refs/heads/main/wampus-ia.png',
    link: 'https://github.com/pintomultimedia2002/A_star_algorithm_Javascript',
    tools: [T.JS, 'Pathfinding', 'Algoritmos'],
    category: CAT.DEV,
    context: CTX.UNIV,
  },
  {
    title: 'CarVoice Assistant',
    desc: 'Virtual assistant for vehicles with voice control.',
    fileName: 'https://raw.githubusercontent.com/pintomultimedia2002/carvoice-assist/refs/heads/main/assets/asistant-2.png',
    link: 'https://github.com/pintomultimedia2002/carvoice-assist',
    tools: [T.HTML, T.CSS, T.JS, T.FRONT, 'Web Design', 'Voiceflow', 'Chatbot', T.WEB],
    category: CAT.DEV,
    context: CTX.UNIV,
  },
  {
    title: 'Algebrain Mobile App',
    desc: 'Educational app for algebra focused on user experience.',
    fileName: 'https://raw.githubusercontent.com/pintomultimedia2002/Algebrain-App/refs/heads/main/resources/images/algebrain-demo-4.png',
    link: 'https://github.com/pintomultimedia2002/Algebrain-App',
    tools: [T.HTML, T.CSS, T.JS, T.FRONT, 'Web Design', 'eLearning', 'Web App', 'Mobile', T.WEB],
    category: CAT.DEV,
    context: CTX.UNIV,
  },
  {
    title: '360° VR experience',
    category: CAT.DEV,
    context: CTX.UNIV,
    fileName: 'audio-video-360.avif',
    link: 'https://www.youtube.com/watch?v=Z8sgOhYMAl4',
    desc: 'Horror experience in Virtual Reality rendered in Unity.',
    tools: [T.UNITY, 'VR', 'Audio 3D', T.CS, 'Immersiva', '360°', 'Video', 'Audio', 'XR'],
  },
  {
    title: 'OpenGL 3D simulation',
    category: CAT.DEV,
    context: CTX.UNIV,
    fileName: 'unity-opengl-web.avif',
    link: 'https://relaxed-valkyrie-75101a.netlify.app/',
    desc: 'Simulated collecting minigame with basic physics.',
    tools: [T.UNITY, 'Simulación', '3D', 'Físicas', 'WebGL', T.WEB, T.CS],
  },
  {
    title: 'New Sporify: Sonórus',
    category: CAT.DES,
    context: CTX.UNIV,
    fileName: 'Sonorus-Figma.avif',
    link: 'https://www.figma.com/design/lClUfMJDAuqfEhvXN6IN2B/Untitled?node-id=0-1&t=UD8TxB4UupRydWWD-1',
    desc: 'Alternative interface design (Redesign) for Spotify.',
    tools: [T.FIGMA, 'UI Design', 'Prototyping', 'Redesign', T.UI, T.UX, 'Mobile Design'],
  },
  {
    title: '4 Better Pets App',
    category: CAT.DES,
    context: CTX.UNIV,
    fileName: '4better-pets-app.avif',
    link: 'https://www.figma.com/design/8LDG3cejNOO7Re9Z6MMrfU/4-BETTER-PETS?node-id=0-1&t=fkQtYiNLOuIEM5Uo-1',
    desc: 'Mobile app to facilitate the adoption of pets.',
    tools: [T.FIGMA, 'UX Research', 'Mobile Design', 'Prototyping', T.UI, T.UX, 'App Design'],
  },
  {
    title: 'Rappi UI Redesign',
    category: CAT.DES,
    context: CTX.UNIV,
    fileName: 'RedisenoRappi-Figma.avif',
    link: 'https://www.figma.com/design/W8tY2RtS3hM7B9BQjJgpiB/David-Pinto---Redise%C3%B1o-Rappi?node-id=0-1&t=UmSvMcQEsiyU7y4s-1',
    desc: 'Redesign proposal to improve Rappi\'s UX.',
    tools: [T.FIGMA, 'UI Kit', 'Redesign', T.UI, T.UX, 'App Design'],
  },
  {
    title: 'In-Mortal Transmedia',
    desc: 'Transmedia narrative exploration of the evolution of ideas.',
    fileName: 'https://static.wixstatic.com/media/5d4a70_7d7ad22b0b4f4defbc347b359909bcb1~mv2.jpg/v1/fill/w_2146,h_1229,al_c,q_90,enc_avif,quality_auto/5d4a70_7d7ad22b0b4f4defbc347b359909bcb1~mv2.jpg',
    link: 'https://pintodavid2002.wixsite.com/in-mortal',
    tools: ['Storytelling', 'Wix', 'Concept Art', 'Narrative', 'Transmedia', 'Web Design', T.WEB, T.UX],
    category: CAT.DEV,
    context: CTX.PERS,
  },
  {
    title: 'Planty: Instructional Video',
    date: '2023-05-20',
    channel: 'CLIENTE',
    link: 'https://www.youtube.com/watch?v=1AMhkDXVkqU',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Planty: Behind the Scenes',
    date: '2023-05-25',
    channel: 'CLIENTE',
    link: 'https://www.youtube.com/watch?v=scgv4lL-4vk',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Antioquia Missionary Church',
    date: '2021-07-15',
    channel: 'CLIENTE',
    link: 'https://www.youtube.com/watch?v=zi_l5z1Yx6s',
    category: CAT.VID,
    context: CTX.PERS,
  },
  {
    title: 'Trailer App: Algebrain',
    date: '2024-02-10',
    channel: 'PROMO',
    link: 'https://www.youtube.com/watch?v=9rP3nJe5S4g',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'GymApp Parody Commercial',
    date: '2024-01-15',
    channel: 'COMERCIAL',
    link: 'https://www.youtube.com/watch?v=QWK7JctMbug',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Radio soap opera Suspense',
    date: '2023-06-10',
    channel: 'ARCHIVO',
    link: 'https://www.youtube.com/watch?v=VJC3mEY-dFU',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Minidocumentary: Electronic Art',
    date: '2022-11-10',
    channel: 'DOCU',
    link: 'https://www.youtube.com/watch?v=P4X0pvVxqVE',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Brainstorming: Project Brock',
    date: '2022-09-05',
    channel: 'ARCHIVO',
    link: 'https://www.youtube.com/watch?v=ijmfr-FB1dM',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Stop Motion: Pixelation',
    date: '2022-04-15',
    channel: 'ANIMACIÓN',
    link: 'https://www.youtube.com/watch?v=ui06UdetAPg',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Visual Narrative: Ethics',
    date: '2020-08-20',
    channel: 'ARCHIVO',
    link: 'https://www.youtube.com/watch?v=DR1FwQc-9rQ',
    context: CTX.UNIV,
    category: CAT.VID,
  },
  {
    title: 'Synchronized 3D Render',
    date: '2023-11-15',
    channel: 'ARCHIVO',
    link: 'https://www.youtube.com/watch?v=VcCDOt0Uujk',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: '3D Animated Sack',
    date: '2023-10-20',
    channel: 'ARCHIVO',
    link: 'https://www.youtube.com/watch?v=wKekfdNC3ZY',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Playblast Electro Swing',
    date: '2023-09-05',
    channel: 'ARCHIVO',
    link: 'https://youtu.be/v3VPVmA7qOs',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Playblast & Edit Cops',
    date: '2023-08-15',
    channel: 'ARCHIVO',
    link: 'https://youtu.be/V3ABRvOuce0',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Timelapse Dev: GymApp',
    date: '2024-01-20',
    channel: 'DEVLOG',
    link: 'https://www.youtube.com/watch?v=ANcyGAwcUac',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Digital Drawing: My Beginnings',
    date: '2022-03-20',
    channel: 'ARTE',
    link: 'https://www.youtube.com/watch?v=QV04Wh2BU0E',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Java OOP Explanation',
    date: '2020-05-15',
    channel: 'TUTORIAL',
    link: 'https://www.youtube.com/watch?v=qIxRbcXezWU',
    category: CAT.VID,
    context: CTX.UNIV,
  },];

/* ========================================================================
   2. GALERÍA VISUAL (ARTE)
   ======================================================================== */
window.galleryData = [];
