/* ========================================================================
   OPTIMIZACIÓN DE TAXONOMÍA (Ahorro de bytes y consistencia)
   ======================================================================== */
window.CTX = {
  PROF: 'PROFESSIONAL',
  UNIV: 'UNIVERSITY',
  PERS: 'PERSONAL',
};

window.CAT = {
  DEV: 'DEV',
  DES: 'DESIGN',
  VID: 'VIDEO',
  ART: 'ART',
};

// Herramientas más repetidas (Opcional, pero ayuda mucho a reducir peso)
window.T = {
  HTML: 'HTML',
  CSS: 'CSS',
  JS: 'Javascript',
  CS: 'C#',
  UNITY: 'Unity',
  FIGMA: 'Figma',
  WEB: 'Web',
  FRONT: 'Frontend',
  UI: 'UI',
  UX: 'UX',
  PHOTO: 'Photoshop',
  ILUS: 'Ilustrator',
  UNREAL: 'Unreal Engine',
  MAYA: 'Autodesk Maya',
  DAVINCI: 'DaVinci Resolve',
  EDIT: 'Edición de Video',
  VID: 'Video',
  YT: 'YouTube',
  THUMB: 'Miniaturas',
  TW: 'Twitch',
  COM: 'Comunitario',
  PY: 'Python',
  SCR: 'Script',
  SOFT: 'Software',
};

window.PROJECT_CONFIG = {
  paths: {
    [CAT.DEV]: '../assets/images/dev/',
    [CAT.DES]: '../assets/images/design/',
    [CAT.ART]: '../assets/images/ilustraciones/',
    [CAT.VID]: '../assets/images/video/', // Opcional
    DEFAULT: '../assets/images/',
  },
};

/* ========================================================================
   1. PORTAFOLIO PRINCIPAL (DEV + DESIGN + VIDEO)
   ======================================================================== */
window.mainPortfolio = [
  {
    title: 'Universal Portfolio Local DB Manager',
    fileName: 'https://raw.githubusercontent.com/Tarquitet/portfolio-updater/main/images/README/1769443128324.png',
    link: 'https://github.com/Tarquitet/portfolio-updater',
    desc: 'Helper for updating my profile website automated',
    tools: [T.PY, T.SCR, T.SOFT, T.COM],
    category: CAT.DEV,
    context: CTX.PERS,
  },
  {
    title: 'Project Manager & Build Orchestrator',
    fileName: 'https://raw.githubusercontent.com/Tarquitet/web-portfolio-manager/main/images/README/1769443877856.png',
    link: 'https://github.com/Tarquitet/web-portfolio-manager',
    desc: 'Automatized helper (translator + minify + portfolio updater) for my official website',
    tools: [T.PY, T.SCR, T.SOFT, T.COM],
    category: CAT.DEV,
    context: CTX.PERS,
  },
  {
    title: 'JSON Auto-Translator (i18n Tool)',
    fileName: 'translator-py',
    link: 'https://github.com/Tarquitet/web-translator',
    desc: 'Auto-translator for every kinda of plain text files if you need to automatize your process updating your web site text files into another lang',
    tools: [T.PY, T.SCR, T.SOFT, T.COM],
    category: CAT.DEV,
    context: CTX.PERS,
  },
  {
    title: 'Asset Optimizer (CSS / JS Minifier)',
    fileName: 'minify-py',
    link: 'https://github.com/Tarquitet/minify-asset-optimizer',
    desc: 'This script helps you fixing some errores using minify like deleting unnecesary lists, break lines, some spaces to identify other objects.',
    tools: [T.PY, T.SCR, T.SOFT, T.COM],
    category: CAT.DEV,
    context: CTX.PERS,
  },
  {
    title: 'OGG CONVERTER/COMPRESSOR',
    fileName: 'https://raw.githubusercontent.com/Tarquitet/ogg-convertor/main/images/README/1769445521124.png',
    link: 'https://github.com/Tarquitet/ogg-convertor',
    desc: 'Bro, why u need to download more than 1GB on audio when you can compress those files a little more to saving time and space?',
    tools: [T.PY, T.SCR, T.SOFT, T.COM],
    category: CAT.DEV,
    context: CTX.PERS,
  },
  {
    title: 'HTML 2 PDF',
    fileName: 'https://raw.githubusercontent.com/Tarquitet/html-2-pdf/main/images/README/1769443738317.png',
    link: 'https://github.com/Tarquitet/html-2-pdf',
    desc: 'Simple python program to conver html 2 pdf.',
    tools: [T.PY, T.SCR, T.SOFT, T.COM],
    category: CAT.DEV,
    context: CTX.PERS,
  },
  {
    title: 'Offline Image Compressor',
    category: CAT.DEV,
    context: CTX.PERS,
    fileName: 'https://raw.githubusercontent.com/Tarquitet/image-conversor/main/images/README/1769206951282.avif',
    link: 'https://github.com/Tarquitet/image-conversor',
    desc: 'This project was made for optimize some images for my personal website. Of course, there are so many websites that can do the same thing, but- You need to pay for more. So. Why not trying myself?',
    tools: [T.PY, T.SCR, T.SOFT, T.COM],
  },
  {
    title: 'Minecraft UUID Converter',
    fileName: 'https://raw.githubusercontent.com/Tarquitet/minecraft_uuid_converter/refs/heads/main/images/README/1769448117738.png',
    link: 'https://github.com/Tarquitet/minecraft_uuid_converter.git',
    desc: 'Python program that allows to renaming uuid players files or finding uuids from mojang, elyby, offline auth',
    tools: [T.PY, T.SCR, T.SOFT, T.COM],
    category: CAT.DEV,
    context: CTX.PERS,
  },
  {
    title: 'Invitación para boda',
    fileName: 'boda_hermano_1_persona',
    link: '=',
    desc: 'El cliente había solicitado un diseño similar que había encontrado por internet con ligeros cambios. He aquí, el trabajo completo.',
    tools: [T.PHOTO, T.THUMB, T.VID, T.YT],
    category: CAT.DES,
    context: CTX.PERS,
  },
  {
    title: 'Miniatura para video nostálgico de Minecraft',
    fileName: 'Minecraft-en-2010',
    link: '=',
    desc: 'Diseño para una miniatura sobre las fases tempranas del desarrollo del videojuego de Minecraft',
    tools: [T.PHOTO, T.THUMB, T.VID, T.YT],
    category: CAT.DES,
    context: CTX.PERS,
  },
  {
    title: 'Mini-edit: Invitación Semana Santa',
    link: 'https://youtube.com/shorts/Fgi9CA35Onc?feature=share',
    desc: 'Video corto sobre una invitación para Semana Santa',
    tools: [T.DAVINCI, T.EDIT, T.VID, T.YT],
    category: CAT.VID,
    context: CTX.PERS,
  },
  {
    title: 'Muestra Realidad Aumentada Modelado 3D',
    link: 'https://youtube.com/shorts/b6hb9cotBcM?feature=share',
    desc: 'Muestra Modelado 3D en Realidad Aumentada usando Maya y unity',
    tools: [T.MAYA, T.UNITY, T.VID, T.YT],
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Ending overlay for Twitch',
    fileName: 'Fondo-offline-v1',
    link: 'https://www.twitch.tv/tarquitet',
    desc: 'Diseño para un overlay para directos en plataformas como Youtube o Twitch',
    tools: [T.PHOTO, T.TW, T.VID, T.YT],
    category: CAT.DES,
    context: CTX.PERS,
  },
  {
    title: 'Logo G.O.U.G',
    fileName: 'GOUG-logo',
    link: 'https://www.curseforge.com/minecraft/modpacks/goug-optimized',
    desc: 'Logo para el modpack de minecraft G.O.U.G',
    tools: [T.PHOTO],
    category: CAT.DES,
    context: CTX.PERS,
  },
  {
    title: 'Rediseño Logo - Instituto Biblico',
    fileName: 'IBHOREB-1',
    link: '=',
    desc: 'Rediseño para el logo del Instituto Bíblico Horeb',
    tools: [T.PHOTO],
    category: CAT.DES,
    context: CTX.PROF,
  },
  {
    title: 'Anuncio frontal - Iglesia',
    fileName: 'IUJ-GLORIA',
    link: '=',
    desc: 'Anuncio frontal para ser impreso y expuesto en frente de una iglesia local',
    tools: [T.PHOTO],
    category: CAT.DES,
    context: CTX.PROF,
  },
  {
    title: 'Miniatura sobre como instalar un modpack en Minecraft',
    fileName: 'NostalgiCraft-Modpack',
    link: '=',
    desc: 'Diseño para una miniatura para un modpack de exploración en Minecraft',
    tools: [T.PHOTO, T.THUMB, T.VID, T.YT],
    category: CAT.DES,
    context: CTX.PERS,
  },
  {
    title: 'Maqueticazión de oferta laboral ATOM Solutions S.A.S',
    fileName: 'oferta_laboral_tecnico',
    link: '=',
    desc: 'Maquetación (Layout Design) para una oferta laboral de ATOMS Solutions',
    tools: [T.PHOTO],
    category: CAT.DES,
    context: CTX.PROF,
  },
  {
    title: 'Edit Fotograma canción Cities in Dust',
    fileName: 'Edicion_Fotograma_CitiesInDust',
    link: '=',
    desc: 'Edición rápida en menos de 1 hora sobre un fotograma del videoclip musical Cities in Dust',
    tools: [T.PHOTO, T.VID],
    category: CAT.DES,
    context: CTX.UNIV,
  },
  {
    title: 'Comic Final Materia Render - Universidad',
    fileName: 'preview-comic-render',
    link: '=',
    desc: 'Render final sobre un cómic realizado individual para la materia de Render en la universidad',
    tools: [T.MAYA, T.PHOTO],
    category: CAT.DES,
    context: CTX.PERS,
  },
  {
    title: 'Propuesta Mockup Día Multiemdia',
    fileName: 'smartmockups_l7w4oeot',
    link: '=',
    desc: 'Propuesta para un logo con su respectivo mockup para el dái del ingeniero multimedia en 2022',
    tools: [T.ILUS, T.PHOTO],
    category: CAT.DES,
    context: CTX.UNIV,
  },
  {
    title: 'Retro CGI Art #02',
    fileName: 'test_2',
    link: '=',
    desc: 'Segundo diseño inspirado en el CGI Retro del antes de los 2000',
    tools: [T.MAYA, T.PHOTO],
    category: CAT.DES,
    context: CTX.PERS,
  },
  {
    title: 'Retro CGI Art #01',
    fileName: 'test_3',
    link: '=',
    desc: 'Primer diseño inspirado en el CGI Retro del antes de los 2000',
    tools: [T.MAYA, T.PHOTO],
    category: CAT.DES,
    context: CTX.PERS,
  },
  {
    title: 'Fancy Land Logo',
    fileName: 'Texto-Fancy-Land',
    link: '=',
    desc: 'Diseño de logo para una serie de Minecraft',
    tools: [T.PHOTO],
    category: CAT.DES,
    context: CTX.PERS,
  },
  {
    title: 'Los sueños hechos realidad',
    fileName: 'Transmedia - composicion narrativa - Montaje Final - David Pinto',
    link: '=',
    desc: 'Diseño sobre la expresión de un mundo onírico en la realidad',
    tools: [T.PHOTO],
    category: CAT.DES,
    context: CTX.UNIV,
  },
  {
    title: 'Diseño de niveles con Unreal Engine',
    fileName: 'unreal5',
    link: '=',
    desc: 'Diseño de luces y niveles para un proyecto de diplomado',
    tools: [T.CS, T.UNREAL],
    category: CAT.DEV,
    context: CTX.UNIV,
  },
  {
    title: 'Diseño logo para Ministerio Verdad & Fe',
    fileName: 'V&F-6',
    link: 'https://www.verdadyfe.org/',
    desc: 'Rediseño de logo para el ministerio Verdad & Fe',
    tools: [T.PHOTO],
    category: CAT.DES,
    context: CTX.PROF,
  },
  {
    title: 'Parkour en Minecraft',
    fileName: '200-Parkours---reto-1',
    link: '=',
    desc: 'Diseño de miniatura sobre la idea para un video de Youtube',
    tools: [T.PHOTO, T.THUMB, T.VID, T.YT],
    category: CAT.DES,
    context: CTX.PERS,
  },
  {
    title: 'Página Web Ministerial',
    desc: 'Landing Page oficial para el ministerio Verdad & Fe.',
    fileName: 'verdadyfe',
    link: 'https://www.verdadyfe.org/',
    tools: [T.HTML, T.CSS, T.JS, T.FRONT, 'SEO'],
    category: CAT.DEV,
    context: CTX.PROF,
  },
  {
    title: 'Tarquitet Site Oficial',
    desc: 'Página web oficial del portafolio de Tarquitet.',
    fileName: 'tarquitet-site',
    link: '#',
    tools: [T.HTML, T.CSS, T.JS, 'Portfolio', T.FRONT, 'Web Design', 'Backend'],
    category: CAT.DEV,
    context: CTX.PROF,
  },
  {
    title: 'Tarquitet Old Site',
    desc: 'Anterior diseño web del portafolio oficial de Tarquitet.',
    fileName: 'tarquitet-old-site',
    link: '/ver1/index.html',
    tools: [T.HTML, T.CSS, T.JS, 'Portfolio', T.FRONT, 'Web Design', 'Backend'],
    category: CAT.DEV,
    context: CTX.PROF,
  },
  {
    title: 'Builtechraft Web',
    desc: 'Página web para un proyecto personal sobre un servidor multijugador.',
    fileName: 'Builtechraft-web-2024',
    link: 'https://tarquitet.github.io/Builtechraft-Web/',
    tools: [T.HTML, T.CSS, T.JS, T.FRONT, 'Web Design', 'Minecraft', T.WEB],
    category: CAT.DEV,
    context: CTX.UNIV,
  },
  {
    title: 'App Gimnasio 3D Virtual',
    desc: 'App móvil con ejercicios en vista 360° y explicación biomecánica.',
    fileName: 'https://raw.githubusercontent.com/pintomultimedia2002/GymApp_1_2024/refs/heads/main/Assets/prototipo-demo.png',
    link: 'https://github.com/pintomultimedia2002/GymApp_1_2024',
    tools: [T.UNITY, T.CS, 'UI Mobile'],
    category: CAT.DEV,
    context: CTX.UNIV,
  },
  {
    title: 'Sudoku Intelligent Solver',
    desc: 'IA que genera y resuelve Sudokus mediante Backtracking eficiente.',
    fileName: 'https://raw.githubusercontent.com/pintomultimedia2002/Sudoku_Intelligent_Backtracking/refs/heads/master/sudokugenerado.png',
    link: 'https://github.com/pintomultimedia2002/Sudoku_Intelligent_Backtracking',
    tools: [T.CS, 'Backtracking', 'IA'],
    category: CAT.DEV,
    context: CTX.UNIV,
  },
  {
    title: 'C.I.P.S Puzzle Solver',
    desc: 'Minijuego sobre IA experimental que resuelve puzzles numéricos.',
    fileName: 'https://raw.githubusercontent.com/pintomultimedia2002/CIPS_Intelligent_Puzzle_Solver/refs/heads/master/puzzle-solved.jpg',
    link: 'https://github.com/pintomultimedia2002/CIPS_Intelligent_Puzzle_Solver',
    tools: [T.CS, 'Heurística', 'IA'],
    category: CAT.DEV,
    context: CTX.UNIV,
  },
  {
    title: 'Wumpus World Agent',
    desc: 'Simulación de un Agente Racional basado en lógica proposicional.',
    fileName: 'https://raw.githubusercontent.com/pintomultimedia2002/wumpus-world-javascript/refs/heads/main/src/resources/wampus.png',
    link: 'https://github.com/pintomultimedia2002/wumpus-world-javascript',
    tools: [T.JS, 'Lógica', 'IA Clásica'],
    category: CAT.DEV,
    context: CTX.UNIV,
  },
  {
    title: 'A* Pathfinder Algorithm',
    desc: 'Implementación del algoritmo A* para búsqueda de caminos óptimos.',
    fileName: 'https://raw.githubusercontent.com/pintomultimedia2002/A_star_algorithm_Javascript/refs/heads/main/wampus-ia.png',
    link: 'https://github.com/pintomultimedia2002/A_star_algorithm_Javascript',
    tools: [T.JS, 'Pathfinding', 'Algoritmos'],
    category: CAT.DEV,
    context: CTX.UNIV,
  },
  {
    title: 'CarVoice Assistant',
    desc: 'Asistente virtual para vehículos con control por voz.',
    fileName: 'https://raw.githubusercontent.com/pintomultimedia2002/carvoice-assist/refs/heads/main/assets/asistant-2.png',
    link: 'https://github.com/pintomultimedia2002/carvoice-assist',
    tools: [T.HTML, T.CSS, T.JS, T.FRONT, 'Web Design', 'Voiceflow', 'Chatbot', T.WEB],
    category: CAT.DEV,
    context: CTX.UNIV,
  },
  {
    title: 'Algebrain Mobile App',
    desc: 'App educativa para álgebra enfocada en la experiencia de usuario.',
    fileName: 'https://raw.githubusercontent.com/pintomultimedia2002/Algebrain-App/refs/heads/main/resources/images/algebrain-demo-4.png',
    link: 'https://github.com/pintomultimedia2002/Algebrain-App',
    tools: [T.HTML, T.CSS, T.JS, T.FRONT, 'Web Design', 'eLearning', 'Web App', 'Mobile', T.WEB],
    category: CAT.DEV,
    context: CTX.UNIV,
  },
  {
    title: 'Experiencia 360° VR',
    desc: 'Experiencia de terror en Realidad Virtual renderizada en Unity.',
    fileName: 'audio-video-360',
    link: 'https://www.youtube.com/watch?v=Z8sgOhYMAl4',
    tools: [T.UNITY, 'VR', 'Audio 3D', T.CS, 'Immersiva', '360°', 'Video', 'Audio', 'XR'],
    category: CAT.DEV,
    context: CTX.UNIV,
  },
  {
    title: 'Simulación OpenGL 3D',
    desc: 'Minijuego de recolección simulado con físicas básicas.',
    fileName: 'unity-opengl-web',
    link: 'https://relaxed-valkyrie-75101a.netlify.app/',
    tools: [T.UNITY, 'Simulación', '3D', 'Físicas', 'WebGL', T.WEB, T.CS],
    category: CAT.DEV,
    context: CTX.UNIV,
  },
  {
    title: 'New Sporify: Sonórus',
    desc: 'Diseño de interfaz alternativa (Redesign) para Spotify.',
    fileName: 'Sonorus-Figma',
    link: 'https://www.figma.com/design/lClUfMJDAuqfEhvXN6IN2B/Untitled?node-id=0-1&t=UD8TxB4UupRydWWD-1',
    tools: [T.FIGMA, 'UI Design', 'Prototyping', 'Redesign', T.UI, T.UX, 'Mobile Design'],
    category: CAT.DES,
    context: CTX.UNIV,
  },
  {
    title: '4 Better Pets App',
    desc: 'App móvil para facilitar la adopción de mascotas.',
    fileName: '4better-pets-app',
    link: 'https://www.figma.com/design/8LDG3cejNOO7Re9Z6MMrfU/4-BETTER-PETS?node-id=0-1&t=fkQtYiNLOuIEM5Uo-1',
    tools: [T.FIGMA, 'UX Research', 'Mobile Design', 'Prototyping', T.UI, T.UX, 'App Design'],
    category: CAT.DES,
    context: CTX.UNIV,
  },
  {
    title: 'Rappi UI Redesign',
    desc: 'Propuesta de rediseño para mejorar la UX de Rappi.',
    fileName: 'RedisenoRappi-Figma',
    link: 'https://www.figma.com/design/W8tY2RtS3hM7B9BQjJgpiB/David-Pinto---Redise%C3%B1o-Rappi?node-id=0-1&t=UmSvMcQEsiyU7y4s-1',
    tools: [T.FIGMA, 'UI Kit', 'Redesign', T.UI, T.UX, 'App Design'],
    category: CAT.DES,
    context: CTX.UNIV,
  },
  {
    title: 'In-Mortal Transmedia',
    desc: 'Exploración narrativa transmedia sobre la evolución de las ideas.',
    fileName: 'https://static.wixstatic.com/media/5d4a70_7d7ad22b0b4f4defbc347b359909bcb1~mv2.jpg/v1/fill/w_2146,h_1229,al_c,q_90,enc_avif,quality_auto/5d4a70_7d7ad22b0b4f4defbc347b359909bcb1~mv2.jpg',
    link: 'https://pintodavid2002.wixsite.com/in-mortal',
    tools: ['Storytelling', 'Wix', 'Concept Art', 'Narrative', 'Transmedia', 'Web Design', T.WEB, T.UX],
    category: CAT.DEV,
    context: CTX.PERS,
  },
  {
    title: 'Planty: Video Instruccional',
    date: '2023-05-20',
    channel: 'CLIENTE',
    link: 'https://www.youtube.com/watch?v=1AMhkDXVkqU',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Planty: Detrás de Cámaras',
    date: '2023-05-25',
    channel: 'CLIENTE',
    link: 'https://www.youtube.com/watch?v=scgv4lL-4vk',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Iglesia Misionera Antioquia',
    date: '2021-07-15',
    channel: 'CLIENTE',
    link: 'https://www.youtube.com/watch?v=zi_l5z1Yx6s',
    category: CAT.VID,
    context: CTX.PERS,
  },
  {
    title: 'Trailer App: Algebrain',
    date: '2024-02-10',
    channel: 'PROMO',
    link: 'https://www.youtube.com/watch?v=9rP3nJe5S4g',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Comercial Parodia GymApp',
    date: '2024-01-15',
    channel: 'COMERCIAL',
    link: 'https://www.youtube.com/watch?v=QWK7JctMbug',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Radionovela Suspenso',
    date: '2023-06-10',
    channel: 'ARCHIVO',
    link: 'https://www.youtube.com/watch?v=VJC3mEY-dFU',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Minidocumental: Arte Electrónico',
    date: '2022-11-10',
    channel: 'DOCU',
    link: 'https://www.youtube.com/watch?v=P4X0pvVxqVE',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Brainstorming: Proyecto Brock',
    date: '2022-09-05',
    channel: 'ARCHIVO',
    link: 'https://www.youtube.com/watch?v=ijmfr-FB1dM',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Stop Motion: Pixelation',
    date: '2022-04-15',
    channel: 'ANIMACIÓN',
    link: 'https://www.youtube.com/watch?v=ui06UdetAPg',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Narrativa Visual: Ética',
    date: '2020-08-20',
    channel: 'ARCHIVO',
    link: 'https://www.youtube.com/watch?v=DR1FwQc-9rQ',
    context: CTX.UNIV,
    category: CAT.VID,
  },
  {
    title: 'Render Sincronizado 3D',
    date: '2023-11-15',
    channel: 'ARCHIVO',
    link: 'https://www.youtube.com/watch?v=VcCDOt0Uujk',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Saco Animado 3D',
    date: '2023-10-20',
    channel: 'ARCHIVO',
    link: 'https://www.youtube.com/watch?v=wKekfdNC3ZY',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Playblast Electro Swing',
    date: '2023-09-05',
    channel: 'ARCHIVO',
    link: 'https://youtu.be/v3VPVmA7qOs',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Playblast & Edit Cops',
    date: '2023-08-15',
    channel: 'ARCHIVO',
    link: 'https://youtu.be/V3ABRvOuce0',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Timelapse Dev: GymApp',
    date: '2024-01-20',
    channel: 'DEVLOG',
    link: 'https://www.youtube.com/watch?v=ANcyGAwcUac',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Dibujo Digital: Mis Inicios',
    date: '2022-03-20',
    channel: 'ARTE',
    link: 'https://www.youtube.com/watch?v=QV04Wh2BU0E',
    category: CAT.VID,
    context: CTX.UNIV,
  },
  {
    title: 'Explicación POO Java',
    date: '2020-05-15',
    channel: 'TUTORIAL',
    link: 'https://www.youtube.com/watch?v=qIxRbcXezWU',
    category: CAT.VID,
    context: CTX.UNIV,
  },];

/* ========================================================================
   2. GALERÍA VISUAL (ARTE)
   ======================================================================== */
window.galleryData = [];
